on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven



      - name: Install Chrome
        run: |
            sudo apt-get update
            sudo apt-get install -y chromium-browser

      - name: Install Firefox (stable tar)
        run: |
          wget -q https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US -O firefox.tar.bz2
          tar xjf firefox.tar.bz2
          sudo mv firefox /opt/firefox
          sudo ln -s /opt/firefox/firefox /usr/bin/firefox

      - name: Build and test
        run: |
          echo "Kör alla tester, selenium och unittester..."
          mvn -B clean test